#!/usr/bin/env bash
# installs nginx
# start new server
# create index.html that containg a string

apt-get update
apt-get install -y nginx
mkdir -p /var/www/html
touch /var/www/html/index.html

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80 default_server;
    listen  [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}    
" > /etc/nginx/sites-available/default

service nginx restart
