#!/usr/bin/env bash

# installs nginx
# start new server
# create index.html that containg a string

apt-get update
apt-get install -y nginx

touch /etc/nginx/html/index.html
touch /etc/nginx/html/404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen 80;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404.html {
    	  root /etc/nginx/html;
	  internal;
    }
}    
" > /etc/nginx/sites-available/default

service nginx restart
