#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get update
apt-get install -y haproxy=2.4.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    daemon
    user haproxy
    group haproxy

defaults
    mode    http

listen appname
    bind :80
    balance roundrobin
    server 1066-web-01 35.196.132.109:80 check
    server 1066-web-02 34.238.193.147:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy stop
service haproxy start
