#!/usr/bin/env bash
# display 1-100 with conditionals

i=1

while [ "$i" -le 100 ]
do
    if (( i % 3 == 0 && i % 5 == 0 ))
    then
	echo "FizzBuzz"
	(( i++ ))
	continue
    elif (( i % 3 == 0 ))
    then
	echo "Fizz"
	(( i++ ))
	continue
    elif (( i % 5 == 0 ))
    then
	echo "Buzz"
	(( i++ ))
	continue
    else
	echo $i
	(( i++ ))
    fi
done
