#!/usr/bin/env bash
# using if-else in loops

a=0
while [ $a -lt 10 ]
do
	if [ $a -eq 3 ]
	then
	    echo "bad luck"
	    (( a++ ))
	    continue
	elif [ $a -eq 7 ]
	then
	    echo "good luck"
	    (( a++ ))
	    continue
	else
	    echo "Best School"
	    (( a++ ))
	    continue
	fi
done
